Blockbuster/config/routes.rb
Rails.application.routes.draw do
  resources :kids
  root 'welcome#index'
  # resources :sessions, only: [:new]
  # get 'welcome/index'

  devise_for :users

  resources :show_subscriptions
  resources :news
  resources :chapters
  resources :seasons
  resources :show_reviews
  resources :chapter_views
  resources :shows
  resources :actors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Blockbuster/app/models/actor.rb
class Actor < ApplicationRecord
  has_many :news
  has_many :actorshows
  has_many :shows, through: :actorshows
end

Blockbuster/app/models/actorshow.rb
class Actorshow < ApplicationRecord
	belongs_to :actor
	belongs_to :show
end

Blockbuster/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blockbuster/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :chapter_views
  belongs_to :season
end

Blockbuster/app/models/chapter_view.rb
class ChapterView < ApplicationRecord
  belongs_to :user
  belongs_to :chapter
end

Blockbuster/app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user
end

Blockbuster/app/models/new.rb
class New < ApplicationRecord
  belongs_to :actor
end

Blockbuster/app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show
  has_many :chapters
end

Blockbuster/app/models/show.rb
class Show < ApplicationRecord
  has_many :show_reviews
  has_many :seasons
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :actorshows
  has_many :actors, through: :actorshows

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

end

Blockbuster/app/models/show_review.rb
class ShowReview < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subscriptions
  has_many :shows, through: :subscriptions
  has_many :show_reviews
  has_many :chapter_views
  has_many :kids
end

Blockbuster/app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to edit_user_registration_path, notice: 'La cuenta asociada ha sido creada correctamente.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :user_id)
    end
end

Blockbuster/app/helpers/actors_helper.rb
module ActorsHelper
end

Blockbuster/app/helpers/application_helper.rb
module ApplicationHelper
end

Blockbuster/app/helpers/chapters_helper.rb
module ChaptersHelper
end

Blockbuster/app/helpers/kids_helper.rb
module KidsHelper
end

Blockbuster/app/helpers/news_helper.rb
module NewsHelper
end

Blockbuster/app/helpers/seasons_helper.rb
module SeasonsHelper
end

Blockbuster/app/helpers/sessions_helper.rb
module SessionsHelper
end

Blockbuster/app/helpers/shows_helper.rb
module ShowsHelper
end

Blockbuster/app/helpers/users_helper.rb
module UsersHelper
end

Blockbuster/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Blockbuster/app/views/kids/_form.html.erb
<%= form_for(kid) do |f| %>
  <% if kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blockbuster/app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

Blockbuster/app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.user %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

Blockbuster/app/views/kids/new.html.erb
<h1>Crear cuenta asociada</h1>

<div class="main-form">
	<form class="new_kid" id="new_kid" action="/kids" accept-charset="UTF-8" method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
		<div class="field">
			<input type="num" name="kid[user_id]" id="user_id" value="<%= current_user.id %>" hidden>
		</div>

		<div class="field">
			<label for="kid_name">Nombre</label>
			<input type="text" name="kid[name]" id="kid_name">
		</div>

		<div class="actions">
			<input type="submit" name="commit" value="Crear Cuenta Asociada" data-disable-with="Crear Cuenta Asociada">
		</div>
	</form>
</div>

Blockbuster/app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @kid.user %>
</p>

<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>