Blockbuster/config/routes.rb
Rails.application.routes.draw do
  resources :kids
  root 'welcome#index'
  # resources :sessions, only: [:new]
  # get 'welcome/index'

  devise_for :users

  resources :show_subscriptions
  resources :news
  resources :chapters
  resources :seasons
  resources :show_reviews
  resources :chapter_views
  resources :shows
  resources :actors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Blockbuster/app/models/actor.rb
class Actor < ApplicationRecord
  has_many :news
  has_many :actorshows
  has_many :shows, through: :actorshows
end

Blockbuster/app/models/actorshow.rb
class Actorshow < ApplicationRecord
	belongs_to :actor
	belongs_to :show
end

Blockbuster/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blockbuster/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :chapter_views
  belongs_to :season
end

Blockbuster/app/models/chapter_view.rb
class ChapterView < ApplicationRecord
  belongs_to :user
  belongs_to :chapter
end

Blockbuster/app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user
end

Blockbuster/app/models/new.rb
class New < ApplicationRecord
  belongs_to :actor
end

Blockbuster/app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show
  has_many :chapters
end

Blockbuster/app/models/show.rb
class Show < ApplicationRecord
  has_many :show_reviews
  has_many :seasons
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :actorshows
  has_many :actors, through: :actorshows

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

end

Blockbuster/app/models/show_review.rb
class ShowReview < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subscriptions
  has_many :shows, through: :subscriptions
  has_many :show_reviews
  has_many :chapter_views
  has_many :kids
end

Blockbuster/app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  before_action :set_show, only: [:new]


  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  helper_method :user_has_viewed
  def user_has_viewed(chapter, user)
    cv = ChapterView.find_by(chapter_id: chapter, user_id: user)
    if cv != nil
      return true
    else
      return false
    end
  end

  helper_method :find_chapter_view
  def find_chapter_view(chapter, user)
    cv = ChapterView.find_by(chapter_id: chapter, user_id: user)
    if cv != nil
      return cv
    else
      return false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    def set_show
      if (current_user.role == "Admin" and params[:show_id])
        @show = Show.find(params[:show_id])
      else
        redirect_to :controller => 'shows', :action => 'index'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:title, :show_id, :year)
    end
end

Blockbuster/app/helpers/actors_helper.rb
module ActorsHelper
end

Blockbuster/app/helpers/application_helper.rb
module ApplicationHelper
end

Blockbuster/app/helpers/chapters_helper.rb
module ChaptersHelper
end

Blockbuster/app/helpers/kids_helper.rb
module KidsHelper
end

Blockbuster/app/helpers/news_helper.rb
module NewsHelper
end

Blockbuster/app/helpers/seasons_helper.rb
module SeasonsHelper
end

Blockbuster/app/helpers/sessions_helper.rb
module SessionsHelper
end

Blockbuster/app/helpers/shows_helper.rb
module ShowsHelper
end

Blockbuster/app/helpers/users_helper.rb
module UsersHelper
end

Blockbuster/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Blockbuster/app/views/seasons/_form.html.erb
<div class="main-form">
  <%= form_for(season) do |f| %>
    <% if season.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

        <ul>
        <% season.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :show %>
      <%= f.text_field :show %>
    </div>

    <div class="field">
      <%= f.label :year %>
      <%= f.text_field :year %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

Blockbuster/app/views/seasons/edit.html.erb
<h1>Editando <%= @season.show.title %> / <%= @season.title %></h1>

<%= render 'form', season: @season, class: "main" %>

<%= link_to 'Show', @season %>

Blockbuster/app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seasons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Show</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.title %></td>
        <td><%= season.show %></td>
        <td><%= season.year %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

Blockbuster/app/views/seasons/new.html.erb
<h1>Creando temporada para <%= @show.title %></h1>

<div class="main-form">
	<form class="new_season" id="new_season" action="/seasons" accept-charset="UTF-8" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
	  <div class="field">
	    <label for="season_title">Title</label>
	    <input type="text" name="season[title]" id="season_title">
	  </div>

	  <div class="field">
	    <input type="num" name="season[show_id]" id="season_show" value="<%= @show.id %>" hidden>
	  </div>

	  <div class="field">
	    <label for="season_year">Year</label>
	    <input type="text" name="season[year]" id="season_year">
	  </div>

	  <div class="actions">
	    <input type="submit" name="commit" value="Create Season" data-disable-with="Create Season">
	  </div>
	</form>
</div>

<%= link_to 'Back', seasons_path %>

Blockbuster/app/views/seasons/show.html.erb
<% if notice %>
<alert class="alert alert-info alert-full" ><%= notice %></alert>
<% end %>

<div class="center-content">
  <h1><%= @season.show.title %> <%= @season.title %></h1>
  
  <section class="grid grid-center">
    <% @season.chapters.each do |chapter| %>
      <div style="position: relative;">
        <h4>
          <%= chapter.title %>
          <span><br><%= chapter.length %> min</span>
        </h4>
        <%- if user_has_viewed(chapter.id, current_user.id) %>
        <%= link_to "Visto", find_chapter_view(chapter.id, current_user.id), method: :delete, class: "btn btn-green btn-float" %>
        <% else %>
        <%= link_to "Marcar como visto", {:controller => "chapter_views", :action => "create", :chapter_view => {chapter_id: chapter.id, user_id: current_user.id, review: ""}}, :method=>:post, class: "btn btn-blue btn-float" %>
        <% end -%>
      </div>
    <% end %>

    <span style="display:block;clear:both;"></span>
  </section>


  <%- if user_signed_in? && current_user.role == "Admin" %>
  Herramientas de Administrador 
  <%= link_to 'Editar Temporada', edit_season_path(@season), class: "bright" %> |
  <%= link_to "+ Agregar Capítulo", {:controller => "chapters", :action => "new", :season_id => @season.id}, class: "bright" %>
  <% end -%>
</div>