Blockbuster/config/routes.rb
Rails.application.routes.draw do
  resources :kids
  root 'welcome#index'
  # resources :sessions, only: [:new]
  # get 'welcome/index'

  devise_for :users

  resources :show_subscriptions
  resources :news
  resources :chapters
  resources :seasons
  resources :show_reviews
  resources :chapter_views
  resources :shows
  resources :actors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Blockbuster/app/models/actor.rb
class Actor < ApplicationRecord
  has_many :news
  has_many :actorshows
  has_many :shows, through: :actorshows
end

Blockbuster/app/models/actorshow.rb
class Actorshow < ApplicationRecord
	belongs_to :actor
	belongs_to :show
end

Blockbuster/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blockbuster/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :chapter_views
  belongs_to :season
end

Blockbuster/app/models/chapter_view.rb
class ChapterView < ApplicationRecord
  belongs_to :user
  belongs_to :chapter
end

Blockbuster/app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user
end

Blockbuster/app/models/new.rb
class New < ApplicationRecord
  belongs_to :actor
end

Blockbuster/app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show
  has_many :chapters
end

Blockbuster/app/models/show.rb
class Show < ApplicationRecord
  has_many :show_reviews
  has_many :seasons
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :actorshows
  has_many :actors, through: :actorshows

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

end

Blockbuster/app/models/show_review.rb
class ShowReview < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

Blockbuster/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subscriptions
  has_many :shows, through: :subscriptions
  has_many :show_reviews
  has_many :chapter_views
  has_many :kids
end

Blockbuster/app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_action :set_season, only: [:new]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    def set_season
      if (current_user.role == "Admin" and params[:season_id])
        @season = Season.find(params[:season_id])
      else
        redirect_to :controller => 'shows', :action => 'index'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:length, :season_id, :title)
    end
end

Blockbuster/app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to edit_user_registration_path, notice: 'La cuenta asociada ha sido creada correctamente.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :user_id)
    end
end

Blockbuster/app/helpers/actors_helper.rb
module ActorsHelper
end

Blockbuster/app/helpers/application_helper.rb
module ApplicationHelper
end

Blockbuster/app/helpers/chapters_helper.rb
module ChaptersHelper
end

Blockbuster/app/helpers/kids_helper.rb
module KidsHelper
end

Blockbuster/app/helpers/news_helper.rb
module NewsHelper
end

Blockbuster/app/helpers/seasons_helper.rb
module SeasonsHelper
end

Blockbuster/app/helpers/sessions_helper.rb
module SessionsHelper
end

Blockbuster/app/helpers/shows_helper.rb
module ShowsHelper
end

Blockbuster/app/helpers/users_helper.rb
module UsersHelper
end

Blockbuster/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Blockbuster/app/views/chapters/_form.html.erb
<%= form_for(chapter) do |f| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length %>
  </div>

  <div class="field">
    <%= f.label :season %>
    <%= f.text_field :season %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blockbuster/app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

Blockbuster/app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Length</th>
      <th>Season</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.length %></td>
        <td><%= chapter.season %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

Blockbuster/app/views/chapters/new.html.erb
<h1>Creando capítulo para <%= @season.title %> / <%= @season.show.title %></h1>

<div class="main-form">
	<form class="new_chapter" id="new_chapter" action="/chapters" accept-charset="UTF-8" method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
		<div class="field">
			<input type="num" name="chapter[season_id]" id="chapter_season" value="<%= @season.id %>" hidden>
		</div>

		<div class="field">
			<label for="chapter_title">Título</label>
			<input type="text" name="chapter[title]" id="chapter_title">
		</div>

		<div class="field">
			<label for="chapter_year">Duración</label>
			<input type="text" name="chapter[length]" id="chapter_length">
		</div>

		<div class="actions">
			<input type="submit" name="commit" value="Crear Capítulo" data-disable-with="Crear Capítulo">
		</div>
	</form>
</div>

<%= link_to 'Back', chapters_path %>

Blockbuster/app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @chapter.length %>
</p>

<p>
  <strong>Season:</strong>
  <%= @chapter.season %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>